DICT_USOS = {
    "m111": "Continuous urban fabric",
    "m112": "Discontinuous urban fabric",
    "m121": "Industrial or commercial units",
    "m122": "Road and rail networks and associated land",
    "m123": "Port areas",
    "m124": "Airports",
    "m131": "Mineral extraction sites",
    "m132": "Dump sites",
    "m133": "Construction sites",
    "m141": "Green urban areas",
    "m142": "Sport and leisure facilities",
    "m211": "Non-irrigated arable land",
    "m212": "Permanently irrigated land",
    "m213": "Rice fields",
    "m221": "Vineyards",
    "m222": "Fruit trees and berry plantations",
    "m223": "Olive groves",
    "m231": "Pastures",
    "m241": "Annual crops associated with permanent crops",
    "m242": "Complex cultivation patterns",
    "m243": "Land principally occupied by agriculture, with significant areas of natural vegetation",
    "m244": "Agro-forestry areas",
    "m311": "Broad-leaved forest",
    "m312": "Coniferous forest",
    "m313": "Mixed forest",
    "m321": "Natural grasslands",
    "m322": "Moors and heathland",
    "m323": "Sclerophyllous vegetation",
    "m324": "Transitional woodland-shrub",
    "m331": "Beaches, dunes, sands",
    "m332": "Bare rocks",
    "m333": "Sparsely vegetated areas",
    "m334": "Burnt areas",
    "m335": "Glaciers and perpetual snow",
    "m411": "Inland marshes",
    "m412": "Peat bogs",
    "m421": "Salt marshes",
    "m422": "Salines",
    "m423": "Intertidal flats",
    "m511": "Water courses",
    "m512": "Water bodies",
    "m521": "Coastal lagoons",
    "m522": "Estuaries",
    "m523": "Sea and ocean"
}
