DICT_USOS = {
    "m111": "Tejido urbano continuo",
    "m112": "Tejido urbano discontinuo",
    "m121": "Unidades industriales o comerciales",
    "m122": "Redes de carreteras y ferroviarias y terrenos asociados",
    "m123": "Zonas portuarias",
    "m124": "Aeropuertos",
    "m131": "Zonas de extracción de minerales",
    "m132": "Vertederos",
    "m133": "Obras de construcción",
    "m141": "Zonas verdes urbanas",
    "m142": "Instalaciones deportivas y de ocio",
    "m211": "Tierras de cultivo no irrigadas",
    "m212": "Tierras de regadío permanente",
    "m213": "Arrozales",
    "m221": "Viñedos",
    "m222": "Plantaciones de árboles frutales y bayas",
    "m223": "Olivares",
    "m231": "Pastos",
    "m241": "Cultivos anuales asociados a cultivos permanentes",
    "m242": "Patrones de cultivo complejos",
    "m243": "Tierras ocupadas principalmente por la agricultura, con importantes zonas de vegetación natural",
    "m244": "Zonas agroforestales",
    "m311": "Bosque de hoja ancha",
    "m312": "Bosque de coníferas",
    "m313": "Bosque mixto",
    "m321": "Praderas naturales",
    "m322": "Páramos y brezales",
    "m323": "Vegetación esclerófila",
    "m324": "Bosque-arbusto de transición",
    "m331": "Playas, dunas, arenas",
    "m332": "Rocas desnudas",
    "m333": "Zonas con poca vegetación",
    "m334": "Zonas quemadas",
    "m335": "Glaciares y nieves perpetuas",
    "m411": "Pantanos interiores",
    "m412": "Turberas",
    "m421": "Marismas",
    "m422": "Salinas",
    "m423": "Llanuras intermareales",
    "m511": "Cursos de agua",
    "m512": "Cuerpos de agua",
    "m521": "Lagunas costeras",
    "m522": "Estuarios",
    "m523": "Mar y océano"
}
